In [2]:
import pandas as pd
import numpy as np

In [3]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits= pd.read_csv('tmdb_5000_credits.csv')

In [4]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [5]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [6]:
movies = movies.merge(credits,on='title')

In [7]:
movies.shape

(4809, 23)

In [8]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [9]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 901.7+ KB

In [10]:
# genre
# id
# keywords
# title
# overview
# cast 
# crew

movies = movies[['movie_id','title','keywords','genres','overview','cast','crew']]

In [11]:
movies.head(1)

,movie_id,title,keywords,genres,overview,cast,crew
0,19995,Avatar,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [12]:
movies.isnull().sum()

movie_id    0
title       0
keywords    0
genres      0
overview    3
cast        0
crew        0
dtype: int64

In [13]:
movies.dropna(inplace=True)

In [14]:
movies.duplicated().sum()

0

In [15]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [16]:
import ast

In [17]:
def arrange(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name'])
    return L

In [18]:
arrange('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [19]:
movies['genres'] = movies['genres'].apply(arrange)
movies.head()

,movie_id,title,keywords,genres,overview,cast,crew
0,19995,Avatar,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[Action, Adventure, Crime]",A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[Action, Adventure, Science Fiction]","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [20]:
movies['keywords'] = movies['keywords'].apply(arrange)
movies.head()

,movie_id,title,keywords,genres,overview,cast,crew
0,19995,Avatar,"[culture clash, future, space war, space colon...","[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ...","[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[spy, based on novel, secret agent, sequel, mi...","[Action, Adventure, Crime]",A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[dc comics, crime fighter, terrorist, secret i...","[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[based on novel, mars, medallion, space travel...","[Action, Adventure, Science Fiction]","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [21]:
 #Here We Only collect the top 3 cast from the given cast 
def convert(obj):
    L = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter !=3:
            L.append(i['name'])
            counter+=1
        else:
            break
    return L

In [22]:
movies['cast'] = movies['cast'].apply(convert)
movies.head()

,movie_id,title,keywords,genres,overview,cast,crew
0,19995,Avatar,"[culture clash, future, space war, space colon...","[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ...","[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[spy, based on novel, secret agent, sequel, mi...","[Action, Adventure, Crime]",A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[dc comics, crime fighter, terrorist, secret i...","[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[based on novel, mars, medallion, space travel...","[Action, Adventure, Science Fiction]","John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [23]:
 #Here We Only Want The Director From The Crew
    
def find_director(obj):
    L = []
    counter = 0
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [24]:
movies['crew'] = movies['crew'].apply(find_director)

In [25]:
movies.head(1)

,movie_id,title,keywords,genres,overview,cast,crew
0,19995,Avatar,"[culture clash, future, space war, space colon...","[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]

In [26]:
 # Here we typecast the String into List
    
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [27]:
# Now We Transform The String Into a Single antity so that the recommender model won't we confused
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","")for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","")for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","")for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","")for i in x])

In [28]:
# Now we Add  new Column 'tags' in the movies dataset by concatenate overview,genres,keywords,cast,crew.
movies['tags'] = movies['overview'] + movies['keywords'] + movies['genres'] + movies['cast'] + movies['crew']

In [29]:
movies.head(2)

,movie_id,title,keywords,genres,overview,cast,crew,tags
0,19995,Avatar,"[cultureclash, future, spacewar, spacecolony, ...","[Action, Adventure, Fantasy, ScienceFiction]","[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[ocean, drugabuse, exoticisland, eastindiatrad...","[Adventure, Fantasy, Action]","[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."

In [30]:
# Now create new Dataframe with movie_id,title and tags
new_df = movies[['movie_id','title','tags']]

In [32]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\RISHAB~1\AppData\Local\Temp/ipykernel_9680/3089450492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [33]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\RISHAB~1\AppData\Local\Temp/ipykernel_9680/3214958533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [34]:
new_df['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d action adventure fantasy sciencefiction samworthington zoesaldana sigourneyweaver jamescameron'

In [35]:
new_df['tags'][1]

"captain barbossa, long believed to be dead, has come back to life and is headed to the edge of the earth with will turner and elizabeth swann. but nothing is quite as it seems. ocean drugabuse exoticisland eastindiatradingcompany loveofone'slife traitor shipwreck strongwoman ship alliance calypso afterlife fighter pirate swashbuckler aftercreditsstinger adventure fantasy action johnnydepp orlandobloom keiraknightley goreverbinski"

In [36]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [37]:
import nltk

In [38]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [39]:
def stem(text):
    y = []
    
    for i in text.split():
        y.append(ps.stem(i))
        
    return " ".join(y)

In [40]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\RISHAB~1\AppData\Local\Temp/ipykernel_9680/3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [41]:
new_df['tags'][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d action adventur fantasi sciencefict samworthington zoesaldana sigourneyweav jamescameron'

### Text Vectorization using Bag of Words

In [42]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words ='english')

In [43]:
cv.fit_transform(new_df['tags']).toarray()
vectors = cv.fit_transform(new_df['tags']).toarray()

In [44]:
#len(cv.get_feature_names())
cv.get_feature_names()

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '17th',
 '18',
 '18th',
 '18thcenturi',
 '19',
 '1910',
 '1920',
 '1930',
 '1940',
 '1944',
 '1950',
 '1950s',
 '1960',
 '1960s',
 '1970',
 '1970s',
 '1971',
 '1974',
 '1976',
 '1980',
 '1985',
 '1990',
 '1999',
 '19th',
 '19thcenturi',
 '20',
 '200',
 '2003',
 '2009',
 '20th',
 '21st',
 '23',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '70',
 '80',
 'aaron',
 'aaroneckhart',
 'abandon',
 'abduct',
 'abigailbreslin',
 'abil',
 'abl',
 'aboard',
 'abov',
 'abus',
 'academ',
 'academi',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'acquaint',
 'act',
 'action',
 'actionhero',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'ad',
 'adam',
 'adamsandl',
 'adamshankman',
 'adapt',
 'add',
 'addict',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adrienbrodi',
 'adult',
 'adultanim',
 'adulteri',
 'adulthood',
 'advanc',
 'adventur',
 'adventure',
 'adventures',
 'advertis',
 'advic',
 'advis',
 'affair',
 'affect',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditssting',
 'afterlif',
 'aftermath',
 'ag',
 'age',
 'agediffer',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'aidanquinn',
 'ail',
 'aim',
 'air',
 'airplan',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'alcatraz',
 'alcohol',
 'alecbaldwin',
 'alex',
 'alexkendrick',
 'alfredhitchcock',
 'alfredmolina',
 'ali',
 'alic',
 'alice',
 'alien',
 'alieninvas',
 'alienlife',
 'alienplanet',
 'aliens',
 'alik',
 'aliv',
 'alive',
 'allen',
 'alli',
 'allianc',
 'allow',
 'alon',
 'alongsid',
 'alpacino',
 'alpha',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'alyssa',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfri',
 'amateur',
 'amaz',
 'amazon',
 'ambassador',
 'ambit',
 'ambiti',
 'ambul',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americancivilwar',
 'americanfootbal',
 'americanfootballplay',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amus',
 'amusementpark',
 'amy',
 'amyadam',
 'amysmart',
 'ana',
 'anakin',
 'analyst',
 'anarchiccomedi',
 'ancient',
 'ancientrom',
 'ancientworld',
 'anderson',
 'andi',
 'andiemacdowel',
 'andrew',
 'android',
 'andy',
 'andygarcía',
 'angel',
 'angela',
 'angelabassett',
 'angeles',
 'angelinajoli',
 'anger',
 'angle',
 'angri',
 'ani',
 'anim',
 'animalattack',
 'animalhorror',
 'animals',
 'anjelicahuston',
 'ann',
 'anna',
 'annafari',
 'annakendrick',
 'anne',
 'annehathaway',
 'annemoss',
 'annetteben',
 'anni',
 'annie',
 'anniversari',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'ant',
 'antholog',
 'anthoni',
 'anthonyanderson',
 'anthonyhopkin',
 'anthropomorph',
 'anti',
 'antic',
 'antihero',
 'antiqu',
 'antoinefuqua',
 'antoniobandera',
 'antonyelchin',
 'anyon',
 'anyth',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apocalyps',
 'apocalypse',
 'apocalypt',
 'appar',
 'appear',
 'appl',
 'apple',
 'appoint',
 'appreci',
 'apprentic',
 'approach',
 'april',
 'aquarium',
 'arab',
 'arch',
 'archaeologist',
 'archeolog',
 'archer',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'aris',
 'aristocrat',
 'arm',
 'armi',
 'armor',
 'armsdeal',
 'army',
 'arnold',
 'arnoldschwarzenegg',
 'arrang',
 'arrangedmarriag',
 'arrest',
 'arriv',
 'arrog',
 'art',
 'arthur',
 'artifact',
 'artifici',
 'artificialintellig',
 'artist',
 'ash',
 'ashley',
 'ashleyjudd',
 'ashtonkutch',
 'asia',
 'asian',
 'asid',
 'ask',
 'aspect',
 'aspir',
 'assassin',
 'assault',
 'assembl',
 'assign',
 'assist',
 'assistant',
 'associ',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'atheist',
 'athlet',
 'atom',
 'atomicbomb',
 'attack',
 'attacks',
 'attempt',
 'attend',
 'attent',
 'attic',
 'attitud',
 'attorney',
 'attract',
 'auction',
 'audienc',
 'audit',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'autism',
 'auto',
 'automobilerac',
 'aveng',
 'averag',
 'avoid',
 'await',
 'awak',
 'awaken',
 'awar',
 'award',
 'away',
 'awkward',
 'awri',
 'awry',
 'ax',
 'babe',
 'babi',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backpack',
 'bad',
 'bag',
 'bahama',
 'bail',
 'balanc',
 'ball',
 'ballet',
 'balloon',
 'baltimor',
 'ban',
 'band',
 'bandit',
 'bangkok',
 'banish',
 'bank',
 'banker',
 'bankrobb',
 'bankrobberi',
 'bar',
 'barbrastreisand',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barrylevinson',
 'barrysonnenfeld',
 'bas',
 'base',
 'basebal',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemus',
 'basedontrueev',
 'basedontruestori',
 'basedontvseri',
 'basedonvideogam',
 'basedonyoungadultnovel',
 'basement',
 'basketbal',
 'basketball',
 'bat',
 'batman',
 'battl',
 'battle',
 'battlefield',
 'bay',
 'beach',
 'beam',
 'bear',
 'beard',
 'beast',
 'beat',
 'beauti',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becam',
 'becaus',
 'becki',
 'becom',
 'becominganadult',
 'bed',
 'bedroom',
 'bee',
 'beer',
 'befor',
 'befriend',
 'began',
 'begin',
 'begins',
 'behavior',
 'belief',
 'believ',
 'bell',
 'bella',
 'belong',
 'belov',
 'ben',
 'benaffleck',
 'bend',
 'beneath',
 'benefit',
 'benfost',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstil',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bestfriendsinlov',
 'bet',
 'beth',
 'betray',
 'bettemidl',
 'better',
 'betti',
 'beverli',
 'bibl',
 'bid',
 'big',
 'bigger',
 'biggest',
 'bike',
 'biker',
 'bikini',
 'billhad',
 'billi',
 'billionair',
 'billmurray',
 'billnighi',
 'billpaxton',
 'billpullman',
 'billybobthornton',
 'billycrudup',
 'billycryst',
 'biographi',
 'biolog',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarr',
 'black',
 'blackmag',
 'blackmail',
 'blackpeopl',
 'blacksmith',
 'blade',
 'blame',
 'blend',
 'blind',
 'bliss',
 'blizzard',
 'block',
 'blond',
 'blood',
 'bloodi',
 'bloodsplatt',
 'bloodthirsti',
 'blow',
 'blue',
 'board',
 'boardingschool',
 'boat',
 'bob',
 'bobbi',
 'bobbyfarrelli',
 'bobhoskin',
 'bodi',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bond',
 'bone',
 'book',
 'border',
 'bore',
 'boredom',
 'born',
 'boss',
 'boston',
 'botch',
 'bound',
 'boundari',
 'bounti',
 'bountyhunt',
 'bout',
 'box',
 'boxer',
 'boy',
 'boyfriend',
 'boys',
 'bradleycoop',
 'bradpitt',
 'brain',
 'brainwash',
 'brand',
 'brandon',
 'brave',
 'braveri',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breast',
 'breath',
 'breed',
 'brendanfras',
 'brendangleeson',
 'brent',
 'brettratn',
 'brian',
 'briandepalma',
 'bride',
 'bridesmaid',
 'bridg',
 'brief',
 'brielarson',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'britishsecretservic',
 'brittanymurphi',
 'broadcast',
 'broadway',
 'broke',
 'broken',
 'broker',
 'bronx',
 'brook',
 'brooklyn',
 'broom',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucegreenwood',
 'brucewilli',
 'brutal',
 'bryansing',
 'bu',
 'buck',
 'bud',
 'buddi',
 'buddy',
 'buddycomedi',
 'buddycop',
 'budget',
 'build',
 'building',
 'built',
 'bullet',
 'bulli',
 'bumbl',
 'bunch',
 'bunker',
 'bunni',
 'burglar',
 'buri',
 'burn',
 'bush',
 'busi',
 'business',
 'businessman',
 'bust',
 'butcher',
 'butler',
 'butt',
 'button',
 'buy',
 'buzz',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'california',
 'calvin',
 'camcord',
 'came',
 'camera',
 'cameraman',
 'camerondiaz',
 'camp',
 'campaign',
 'campbell',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candi',
 'candid',
 'canin',
 'cannib',
 'canuxploit',
 'capabl',
 'caper',
 'capit',
 'capt',
 'captain',
 'captiv',
 'captur',
 'capture',
 'car',
 'caraccid',
 'carchas',
 'carcrash',
 'card',
 'care',
 'career',
 'carefre',
 'caretak',
 'careymulligan',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolina',
 'carrac',
 'carri',
 'carrie',
 'cartel',
 'carter',
 'cartoon',
 'caryelw',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castl',
 'cat',
 'cataclysm',
 'catastroph',
 'catch',
 'cateblanchett',
 'catherinedeneuv',
 'catherinekeen',
 'catherinezeta',
 'cathol',
 'catholic',
 'cattl',
 'caught',
 'caus',
 'cavalri',
 'cave',
 'cavemen',
 'celebr',
 'celebration',
 'cell',
 'cellphon',
 'cemeteri',
 'center',
 'centr',
 'central',
 'centuri',
 'centuries',
 'century',
 'ceo',
 'certain',
 'chad',
 'chain',
 'chainsaw',
 'challeng',
 'chamber',
 'champion',
 'championship',
 'chanc',
 'chance',
 'chang',
 'change',
 'changed',
 'changes',
 'channingtatum',
 'chao',
 'chaos',
 'chaotic',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charismat',
 'charl',
 'charli',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charm',
 'chart',
 'chase',
 'chauffeur',
 'chazzpalminteri',
 'cheat',
 'check',
 'cheerlead',
 'chef',
 'chemic',
 'cher',
 'chevychas',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabus',
 'childhero',
 'childhood',
 'childprodigi',
 'children',
 'chill',
 'chimp',
 'china',
 'chines',
 'chip',
 'chipmunk',
 'chiwetelejiofor',
 'chloe',
 'chloëgracemoretz',
 'chloësevigni',
 'chocol',
 'choic',
 'choice',
 'choos',
 'chosen',
 'chowyun',
 'chri',
 'chriscolumbu',
 'chriscoop',
 'chrisevan',
 'chrishemsworth',
 'chrisklein',
 'chrispin',
 'chrisrock',
 'christ',
 'christian',
 'christianbal',
 'christianslat',
 'christin',
 'christinaappleg',
 'christinaricci',
 'christma',
 'christmas',
 'christmasparti',
 'christmastre',
 'christoph',
 'christopherlambert',
 'christopherlloyd',
 'christophernolan',
 'christopherplumm',
 'christopherwalken',
 'christophwaltz',
 'chrisweitz',
 'chronicl',
 'chuck',
 'church',
 'cia',
 'ciaránhind',
 'cigarettesmok',
 'cillianmurphi',
 'cinema',
 'circl',
 'circu',
 'circuit',
 'circumst',
 'citi',
 'citizen',
 'city',
 'civil',
 'civilian',
 'civilwar',
 'claim',
 'clair',
 'clairedan',
 'claireforlani',
 'clan',
 'clark',
 'clash',
 'class',
 'classdiffer',
 'classic',
 'classmat',
 'classroom',
 'claudevandamm',
 'clay',
 'clean',
 'clear',
 'clerk',
 'clever',
 'client',
 'clients',
 'cliff',
 'climat',
 'climb',
 'clinteastwood',
 'cliveowen',
 'clock',
 'clone',
 'close',
 'closer',
 'cloud',
 'clown',
 'club',
 'clue',
 'clueless',
 'clutch',
 'coach',
 'coast',
 'cocain',
 'code',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colin',
 'colinfarrel',
 'colinfirth',
 'collaps',
 'colleagu',
 'collect',
 'collector',
 'colleg',
 'college',
 'collid',
 'collis',
 'colombia',
 'colonel',
 'coloni',
 'color',
 'colorado',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comed',
 'comedi',
 'comedian',
 'comedy',
 'comet',
 'comfort',
 'comic',
 'coming',
 'comingofag',
 'comingout',
 'command',
 'commando',
 'commerci',
 'commiss',
 'commit',
 'common',
 'commun',
 'communist',
 'community',
 'compani',
 'companion',
 'company',
 'compet',
 'competit',
 'competition',
 'complet',
 'complex',
 'complic',
 'compos',
 'compuls',
 'comput',
 'computerviru',
 'conan',
 'concern',
 'concert',
 'concoct',
 'condit',
 'condition',
 'conduct',
 'confeder',
 'confess',
 'confid',
 'confin',
 'conflict',
 'confront',
 'confus',
 'congress',
 'conman',
 'connect',
 'connecticut',
 'connel',
 'connor',
 'conquer',
 'consequ',
 'consequences',
 'conserv',
 'consid',
 'conspir',
 'conspiraci',
 'conspiracy',
 'constant',
 'constantli',
 'construct',
 'consum',
 'contact',
 'contain',
 'contemporari',
 'contend',
 'content',
 'contest',
 'continu',
 'contract',
 'contractor',
 'control',
 'controversi',
 'convent',
 'converg',
 'convers',
 'convict',
 'convinc',
 'cook',
 ...]

In [45]:
from sklearn.metrics.pairwise import cosine_similarity

In [46]:
similarity = cosine_similarity(vectors)

In [47]:
sorted(list(enumerate(similarity[0])),reverse = True,key =lambda x:x[1])[1:7]

[(1216, 0.28676966733820225),
 (2409, 0.26901379342448517),
 (3730, 0.2605130246476754),
 (507, 0.255608593705383),
 (539, 0.25038669783359574),
 (582, 0.24511108480187255)]

In [48]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse = True,key =lambda x:x[1])[1:6]
    
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [1]:
recommend('avtar')

NameError: name 'recommend' is not defined

In [50]:
# new_df.iloc[1216].title

In [51]:
new_df['title'][20]

'The Amazing Spider-Man'

In [ ]:
# !pip install streamlit

In [54]:
new_df['title']

0                                         Avatar
1       Pirates of the Caribbean: At World's End
2                                        Spectre
3                          The Dark Knight Rises
4                                    John Carter
                          ...
4804                                 El Mariachi
4805                                   Newlyweds
4806                   Signed, Sealed, Delivered
4807                            Shanghai Calling
4808                           My Date with Drew
Name: title, Length: 4806, dtype: object

In [55]:
new_df.['title']

{0: 'Avatar',
 1: "Pirates of the Caribbean: At World's End",
 2: 'Spectre',
 3: 'The Dark Knight Rises',
 4: 'John Carter',
 5: 'Spider-Man 3',
 6: 'Tangled',
 7: 'Avengers: Age of Ultron',
 8: 'Harry Potter and the Half-Blood Prince',
 9: 'Batman v Superman: Dawn of Justice',
 10: 'Superman Returns',
 11: 'Quantum of Solace',
 12: "Pirates of the Caribbean: Dead Man's Chest",
 13: 'The Lone Ranger',
 14: 'Man of Steel',
 15: 'The Chronicles of Narnia: Prince Caspian',
 16: 'The Avengers',
 17: 'Pirates of the Caribbean: On Stranger Tides',
 18: 'Men in Black 3',
 19: 'The Hobbit: The Battle of the Five Armies',
 20: 'The Amazing Spider-Man',
 21: 'Robin Hood',
 22: 'The Hobbit: The Desolation of Smaug',
 23: 'The Golden Compass',
 24: 'King Kong',
 25: 'Titanic',
 26: 'Captain America: Civil War',
 27: 'Battleship',
 28: 'Jurassic World',
 29: 'Skyfall',
 30: 'Spider-Man 2',
 31: 'Iron Man 3',
 32: 'Alice in Wonderland',
 33: 'X-Men: The Last Stand',
 34: 'Monsters University',
 35: 'Transformers: Revenge of the Fallen',
 36: 'Transformers: Age of Extinction',
 37: 'Oz: The Great and Powerful',
 38: 'The Amazing Spider-Man 2',
 39: 'TRON: Legacy',
 40: 'Cars 2',
 41: 'Green Lantern',
 42: 'Toy Story 3',
 43: 'Terminator Salvation',
 44: 'Furious 7',
 45: 'World War Z',
 46: 'X-Men: Days of Future Past',
 47: 'Star Trek Into Darkness',
 48: 'Jack the Giant Slayer',
 49: 'The Great Gatsby',
 50: 'Prince of Persia: The Sands of Time',
 51: 'Pacific Rim',
 52: 'Transformers: Dark of the Moon',
 53: 'Indiana Jones and the Kingdom of the Crystal Skull',
 54: 'The Good Dinosaur',
 55: 'Brave',
 56: 'Star Trek Beyond',
 57: 'WALL·E',
 58: 'Rush Hour 3',
 59: '2012',
 60: 'A Christmas Carol',
 61: 'Jupiter Ascending',
 62: 'The Legend of Tarzan',
 63: 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe',
 64: 'X-Men: Apocalypse',
 65: 'The Dark Knight',
 66: 'Up',
 67: 'Monsters vs Aliens',
 68: 'Iron Man',
 69: 'Hugo',
 70: 'Wild Wild West',
 71: 'The Mummy: Tomb of the Dragon Emperor',
 72: 'Suicide Squad',
 73: 'Evan Almighty',
 74: 'Edge of Tomorrow',
 75: 'Waterworld',
 76: 'G.I. Joe: The Rise of Cobra',
 77: 'Inside Out',
 78: 'The Jungle Book',
 79: 'Iron Man 2',
 80: 'Snow White and the Huntsman',
 81: 'Maleficent',
 82: 'Dawn of the Planet of the Apes',
 83: 'The Lovers',
 84: '47 Ronin',
 85: 'Captain America: The Winter Soldier',
 86: 'Shrek Forever After',
 87: 'Tomorrowland',
 88: 'Big Hero 6',
 89: 'Wreck-It Ralph',
 90: 'The Polar Express',
 91: 'Independence Day: Resurgence',
 92: 'How to Train Your Dragon',
 93: 'Terminator 3: Rise of the Machines',
 94: 'Guardians of the Galaxy',
 95: 'Interstellar',
 96: 'Inception',
 97: 'Shin Godzilla',
 98: 'The Hobbit: An Unexpected Journey',
 99: 'The Fast and the Furious',
 100: 'The Curious Case of Benjamin Button',
 101: 'X-Men: First Class',
 102: 'The Hunger Games: Mockingjay - Part 2',
 103: "The Sorcerer's Apprentice",
 104: 'Poseidon',
 105: 'Alice Through the Looking Glass',
 106: 'Shrek the Third',
 107: 'Warcraft',
 108: 'Terminator Genisys',
 109: 'The Chronicles of Narnia: The Voyage of the Dawn Treader',
 110: 'Pearl Harbor',
 111: 'Transformers',
 112: 'Alexander',
 113: 'Harry Potter and the Order of the Phoenix',
 114: 'Harry Potter and the Goblet of Fire',
 115: 'Hancock',
 116: 'I Am Legend',
 117: 'Charlie and the Chocolate Factory',
 118: 'Ratatouille',
 119: 'Batman Begins',
 120: 'Madagascar: Escape 2 Africa',
 121: 'Night at the Museum: Battle of the Smithsonian',
 122: 'X-Men Origins: Wolverine',
 123: 'The Matrix Revolutions',
 124: 'Frozen',
 125: 'The Matrix Reloaded',
 126: 'Thor: The Dark World',
 127: 'Mad Max: Fury Road',
 128: 'Angels & Demons',
 129: 'Thor',
 130: 'Bolt',
 131: 'G-Force',
 132: 'Wrath of the Titans',
 133: 'Dark Shadows',
 134: 'Mission: Impossible - Rogue Nation',
 135: 'The Wolfman',
 136: 'Bee Movie',
 137: 'Kung Fu Panda 2',
 138: 'The Last Airbender',
 139: 'Mission: Impossible III',
 140: 'White House Down',
 141: 'Mars Needs Moms',
 142: 'Flushed Away',
 143: 'Pan',
 144: 'Mr. Peabody & Sherman',
 145: 'Troy',
 146: "Madagascar 3: Europe's Most Wanted",
 147: 'Die Another Day',
 148: 'Ghostbusters',
 149: 'Armageddon',
 150: 'Men in Black II',
 151: 'Beowulf',
 152: 'Kung Fu Panda 3',
 153: 'Mission: Impossible - Ghost Protocol',
 154: 'Rise of the Guardians',
 155: 'Fun with Dick and Jane',
 156: 'The Last Samurai',
 157: 'Exodus: Gods and Kings',
 158: 'Star Trek',
 159: 'Spider-Man',
 160: 'How to Train Your Dragon 2',
 161: 'Gods of Egypt',
 162: 'Stealth',
 163: 'Watchmen',
 164: 'Lethal Weapon 4',
 165: 'Hulk',
 166: 'G.I. Joe: Retaliation',
 167: 'Sahara',
 168: 'Final Fantasy: The Spirits Within',
 169: 'Captain America: The First Avenger',
 170: 'The World Is Not Enough',
 171: 'Master and Commander: The Far Side of the World',
 172: 'The Twilight Saga: Breaking Dawn - Part 2',
 173: 'Happy Feet Two',
 174: 'The Incredible Hulk',
 175: 'The BFG',
 176: 'The Revenant',
 177: 'Turbo',
 178: 'Rango',
 179: 'Penguins of Madagascar',
 180: 'The Bourne Ultimatum',
 181: 'Kung Fu Panda',
 182: 'Ant-Man',
 183: 'The Hunger Games: Catching Fire',
 184: 'Home',
 185: 'War of the Worlds',
 186: 'Bad Boys II',
 187: 'Puss in Boots',
 188: 'Salt',
 189: 'Noah',
 190: 'The Adventures of Tintin',
 191: 'Harry Potter and the Prisoner of Azkaban',
 192: 'Australia',
 193: 'After Earth',
 194: 'Dinosaur',
 195: 'Night at the Museum: Secret of the Tomb',
 196: 'Megamind',
 197: "Harry Potter and the Philosopher's Stone",
 198: 'R.I.P.D.',
 199: 'Pirates of the Caribbean: The Curse of the Black Pearl',
 200: 'The Hunger Games: Mockingjay - Part 1',
 201: 'The Da Vinci Code',
 202: 'Rio 2',
 203: 'X2',
 204: 'Fast Five',
 205: 'Sherlock Holmes: A Game of Shadows',
 206: 'Clash of the Titans',
 207: 'Total Recall',
 208: 'The 13th Warrior',
 209: 'The Bourne Legacy',
 210: 'Batman & Robin',
 211: 'How the Grinch Stole Christmas',
 212: 'The Day After Tomorrow',
 213: 'Mission: Impossible II',
 214: 'The Perfect Storm',
 215: 'Fantastic 4: Rise of the Silver Surfer',
 216: 'Life of Pi',
 217: 'Ghost Rider',
 218: 'Jason Bourne',
 219: "Charlie's Angels: Full Throttle",
 220: 'Prometheus',
 221: 'Stuart Little 2',
 222: 'Elysium',
 223: 'The Chronicles of Riddick',
 224: 'RoboCop',
 225: 'Speed Racer',
 226: 'How Do You Know',
 227: 'Knight and Day',
 228: 'Oblivion',
 229: 'Star Wars: Episode III - Revenge of the Sith',
 230: 'Star Wars: Episode II - Attack of the Clones',
 231: 'Monsters, Inc.',
 232: 'The Wolverine',
 233: 'Star Wars: Episode I - The Phantom Menace',
 234: 'The Croods',
 235: 'Asterix at the Olympic Games',
 236: 'Windtalkers',
 237: "The Huntsman: Winter's War",
 238: 'Teenage Mutant Ninja Turtles',
 239: 'Gravity',
 240: "Dante's Peak",
 241: 'Teenage Mutant Ninja Turtles: Out of the Shadows',
 242: 'Fantastic Four',
 243: 'Night at the Museum',
 244: 'San Andreas',
 245: 'Tomorrow Never Dies',
 246: 'The Patriot',
 247: "Ocean's Twelve",
 248: 'Mr. & Mrs. Smith',
 249: 'Insurgent',
 250: 'The Aviator',
 251: "Gulliver's Travels",
 252: 'The Green Hornet',
 253: '300: Rise of an Empire',
 254: 'The Smurfs',
 255: 'Home on the Range',
 256: 'Allegiant',
 257: 'Real Steel',
 258: 'The Smurfs 2',
 259: 'Speed 2: Cruise Control',
 260: "Ender's Game",
 261: 'Live Free or Die Hard',
 262: 'The Lord of the Rings: The Fellowship of the Ring',
 263: 'Around the World in 80 Days',
 264: 'Ali',
 265: 'The Cat in the Hat',
 266: 'I, Robot',
 267: 'Kingdom of Heaven',
 268: 'Stuart Little',
 269: 'The Princess and the Frog',
 270: 'The Martian',
 271: 'The Island',
 272: 'Town & Country',
 273: 'Gone in Sixty Seconds',
 274: 'Gladiator',
 275: 'Minority Report',
 276: 'Harry Potter and the Chamber of Secrets',
 277: 'Casino Royale',
 278: 'Planet of the Apes',
 279: 'Terminator 2: Judgment Day',
 280: 'Public Enemies',
 281: 'American Gangster',
 282: 'True Lies',
 283: 'The Taking of Pelham 1 2 3',
 284: 'Little Fockers',
 285: 'The Other Guys',
 286: 'Eraser',
 287: 'Django Unchained',
 288: 'The Hunchback of Notre Dame',
 289: "The Emperor's New Groove",
 290: 'The Expendables 2',
 291: 'National Treasure',
 292: 'Eragon',
 293: 'Where the Wild Things Are',
 294: 'Epic',
 295: 'The Tourist',
 296: 'End of Days',
 297: 'Blood Diamond',
 298: 'The Wolf of Wall Street',
 299: 'Batman Forever',
 300: 'Starship Troopers',
 301: 'Cloud Atlas',
 302: "Legend of the Guardians: The Owls of Ga'Hoole",
 303: 'Catwoman',
 304: 'Hercules',
 305: 'Treasure Planet',
 306: 'Land of the Lost',
 307: 'The Expendables 3',
 308: 'Point Break',
 309: 'Son of the Mask',
 310: 'In the Heart of the Sea',
 311: 'The Adventures of Pluto Nash',
 312: 'Green Zone',
 313: 'The Peanuts Movie',
 314: 'The Spanish Prisoner',
 315: 'The Mummy Returns',
 316: 'Gangs of New York',
 317: 'The Flowers of War',
 318: "Surf's Up",
 319: 'The Stepford Wives',
 320: 'Black Hawk Down',
 321: 'The Campaign',
 322: 'The Fifth Element',
 323: 'Sex and the City 2',
 324: 'The Road to El Dorado',
 325: 'Ice Age: Continental Drift',
 326: 'Cinderella',
 327: 'The Lovely Bones',
 328: 'Finding Nemo',
 329: 'The Lord of the Rings: The Return of the King',
 330: 'The Lord of the Rings: The Two Towers',
 331: 'Seventh Son',
 332: 'Lara Croft: Tomb Raider',
 333: 'Transcendence',
 334: 'Jurassic Park III',
 335: 'Rise of the Planet of the Apes',
 336: 'The Spiderwick Chronicles',
 337: 'A Good Day to Die Hard',
 338: 'The Alamo',
 339: 'The Incredibles',
 340: 'Cutthroat Island',
 341: 'Percy Jackson & the Olympians: The Lightning Thief',
 342: 'Men in Black',
 343: 'Toy Story 2',
 344: 'Unstoppable',
 345: 'Rush Hour 2',
 346: 'What Lies Beneath',
 347: 'Cloudy with a Chance of Meatballs',
 348: 'Ice Age: Dawn of the Dinosaurs',
 349: 'The Secret Life of Walter Mitty',
 350: "Charlie's Angels",
 351: 'The Departed',
 352: 'Mulan',
 353: 'Tropic Thunder',
 354: 'The Girl with the Dragon Tattoo',
 355: 'Die Hard: With a Vengeance',
 356: 'Sherlock Holmes',
 357: 'Ben-Hur',
 358: 'Atlantis: The Lost Empire',
 359: 'Alvin and the Chipmunks: The Road Chip',
 360: 'Valkyrie',
 361: "You Don't Mess with the Zohan",
 362: 'Pixels',
 363: 'A.I. Artificial Intelligence',
 364: 'The Haunted Mansion',
 365: 'Contact',
 366: 'Hollow Man',
 367: 'The Interpreter',
 368: 'Percy Jackson: Sea of Monsters',
 369: 'Lara Croft Tomb Raider: The Cradle of Life',
 370: 'Now You See Me 2',
 371: 'The Saint',
 372: 'Spy Game',
 373: 'Mission to Mars',
 374: 'Rio',
 375: 'Bicentennial Man',
 376: 'Volcano',
 377: "The Devil's Own",
 378: 'K-19: The Widowmaker',
 379: 'Conan the Barbarian',
 380: 'Cinderella Man',
 381: 'The Nutcracker: The Untold Story',
 382: 'Seabiscuit',
 383: 'Twister',
 384: 'Cast Away',
 385: 'Happy Feet',
 386: 'The Bourne Supremacy',
 387: 'Air Force One',
 388: "Ocean's Eleven",
 389: 'The Three Musketeers',
 390: 'Hotel Transylvania',
 391: 'Enchanted',
 392: 'Safe House',
 393: '102 Dalmatians',
 394: 'Tower Heist',
 395: 'The Holiday',
 396: 'Enemy of the State',
 397: "It's Complicated",
 398: "Ocean's Thirteen",
 399: 'Open Season',
 400: 'Divergent',
 401: 'Enemy at the Gates',
 402: 'The Rundown',
 403: 'Last Action Hero',
 404: 'Memoirs of a Geisha',
 405: 'The Fast and the Furious: Tokyo Drift',
 406: 'Arthur Christmas',
 407: 'Meet Joe Black',
 408: 'Collateral Damage',
 409: 'All That Jazz',
 410: 'Mirror Mirror',
 411: 'Scott Pilgrim vs. the World',
 412: 'The Core',
 413: 'Nutty Professor II: The Klumps',
 414: 'Scooby-Doo',
 415: 'Dredd',
 416: 'Click',
 417: 'Creepshow',
 418: 'Cats & Dogs 2 : The Revenge of Kitty Galore',
 419: 'Jumper',
 420: 'Hellboy II: The Golden Army',
 421: 'Zodiac',
 422: 'The 6th Day',
 423: 'Bruce Almighty',
 424: 'The Expendables',
 425: 'Mission: Impossible',
 426: 'The Hunger Games',
 427: 'The Hangover Part II',
 428: 'Batman Returns',
 429: 'Over the Hedge',
 430: 'Lilo & Stitch',
 431: "Charlotte's Web",
 432: 'Deep Impact',
 433: 'RED 2',
 434: 'The Longest Yard',
 435: 'Alvin and the Chipmunks: Chipwrecked',
 436: 'Grown Ups 2',
 437: 'Get Smart',
 438: "Something's Gotta Give",
 439: 'Shutter Island',
 440: 'Four Christmases',
 441: 'Robots',
 442: 'Face/Off',
 443: 'Bedtime Stories',
 444: 'Road to Perdition',
 445: 'Just Go with It',
 446: 'Con Air',
 447: 'Eagle Eye',
 448: 'Cold Mountain',
 449: 'The Book of Eli',
 450: 'Flubber',
 451: 'The Haunting',
 452: 'Space Jam',
 453: 'The Pink Panther',
 454: 'The Day the Earth Stood Still',
 455: 'Conspiracy Theory',
 456: 'Fury',
 457: 'Six Days Seven Nights',
 458: 'Yogi Bear',
 459: 'Spirit: Stallion of the Cimarron',
 460: 'Zookeeper',
 461: 'Lost in Space',
 462: 'The Manchurian Candidate',
 463: 'Déjà Vu',
 464: 'Hotel Transylvania 2',
 465: 'Fantasia 2000',
 466: 'The Time Machine',
 467: 'Mighty Joe Young',
 468: 'Swordfish',
 469: 'The Legend of Zorro',
 470: 'What Dreams May Come',
 471: 'Little Nicky',
 472: 'The Brothers Grimm',
 473: 'Mars Attacks!',
 474: 'Evolution',
 475: 'The Edge',
 476: 'Surrogates',
 477: 'Thirteen Days',
 478: 'Daylight',
 479: 'Walking With Dinosaurs',
 480: 'Battlefield Earth',
 481: 'Looney Tunes: Back in Action',
 482: 'Nine',
 483: 'Timeline',
 484: 'The Postman',
 485: 'Babe: Pig in the City',
 486: 'The Last Witch Hunter',
 487: 'Red Planet',
 488: 'Arthur and the Invisibles',
 489: 'Oceans',
 490: 'A Sound of Thunder',
 491: 'Pompeii',
 492: 'Top Cat Begins',
 493: 'A Beautiful Mind',
 494: 'The Lion King',
 495: 'Journey 2: The Mysterious Island',
 496: 'Cloudy with a Chance of Meatballs 2',
 497: 'Red Dragon',
 498: 'Hidalgo',
 499: 'Jack and Jill',
 500: '2 Fast 2 Furious',
 501: 'The Little Prince',
 502: 'The Invasion',
 503: 'The Adventures of Rocky & Bullwinkle',
 504: 'The Secret Life of Pets',
 505: 'The League of Extraordinary Gentlemen',
 506: 'Despicable Me 2',
 507: 'Independence Day',
 508: 'The Lost World: Jurassic Park',
 509: 'Madagascar',
 510: 'Children of Men',
 511: 'X-Men',
 512: 'Wanted',
 513: 'The Rock',
 514: 'Ice Age: The Meltdown',
 515: '50 First Dates',
 516: 'Hairspray',
 517: 'Exorcist: The Beginning',
 518: 'Inspector Gadget',
 519: 'Now You See Me',
 520: 'Grown Ups',
 521: 'The Terminal',
 522: 'Hotel for Dogs',
 523: 'Vertical Limit',
 524: "Charlie Wilson's War",
 525: 'Shark Tale',
 526: 'Dreamgirls',
 527: 'Be Cool',
 528: 'Munich',
 529: 'Tears of the Sun',
 530: 'Killers',
 531: 'The Man from U.N.C.L.E.',
 532: 'Spanglish',
 533: 'Monster House',
 534: 'Bandits',
 535: 'First Knight',
 536: 'Anna and the King',
 537: 'Immortals',
 538: 'Hostage',
 539: 'Titan A.E.',
 540: 'Hollywood Homicide',
 541: 'Soldier',
 542: 'Carriers',
 543: 'Monkeybone',
 544: 'Flight of the Phoenix',
 545: 'Unbreakable',
 546: 'Minions',
 547: 'Sucker Punch',
 548: 'Snake Eyes',
 549: 'Sphere',
 550: 'The Angry Birds Movie',
 551: "Fool's Gold",
 552: 'Funny People',
 553: 'The Kingdom',
 554: 'Talladega Nights: The Ballad of Ricky Bobby',
 555: 'Dr. Dolittle 2',
 556: 'Braveheart',
 557: 'Jarhead',
 558: 'The Simpsons Movie',
 559: 'The Majestic',
 560: 'Driven',
 561: 'Two Brothers',
 562: 'The Village',
 563: 'Doctor Dolittle',
 564: 'Signs',
 565: 'Shrek 2',
 566: 'Cars',
 567: 'Runaway Bride',
 568: 'xXx',
 569: 'The SpongeBob Movie: Sponge Out of Water',
 570: 'Ransom',
 571: 'Inglourious Basterds',
 572: 'Hook',
 573: 'Die Hard 2',
 574: 'S.W.A.T.',
 575: 'Vanilla Sky',
 576: 'Lady in the Water',
 577: 'AVP: Alien vs. Predator',
 578: 'Alvin and the Chipmunks: The Squeakquel',
 579: 'We Were Soldiers',
 580: 'Olympus Has Fallen',
 581: 'Star Trek: Insurrection',
 582: 'Battle: Los Angeles',
 583: 'Big Fish',
 584: 'Wolf',
 585: 'War Horse',
 586: 'The Monuments Men',
 587: 'The Abyss',
 588: 'Wall Street: Money Never Sleeps',
 589: 'Dracula Untold',
 590: 'The Siege',
 591: 'Stardust',
 592: 'Seven Years in Tibet',
 593: 'The Dilemma',
 594: 'Bad Company',
 595: 'Doom',
 596: 'I Spy',
 597: 'Underworld: Awakening',
 598: 'Rock of Ages',
 599: "Hart's War",
 600: 'Killer Elite',
 601: 'Rollerball',
 602: 'Ballistic: Ecks vs. Sever',
 603: 'Hard Rain',
 604: 'Osmosis Jones',
 605: "Legends of Oz: Dorothy's Return",
 606: 'Blackhat',
 607: 'Sky Captain and the World of Tomorrow',
 608: 'Basic Instinct 2',
 609: 'Escape Plan',
 610: 'The Legend of Hercules',
 611: 'The Sum of All Fears',
 612: 'The Twilight Saga: Eclipse',
 613: 'The Score',
 614: 'Despicable Me',
 615: 'Money Train',
 616: 'Ted 2',
 617: 'Agora',
 618: 'Mystery Men',
 619: 'Hall Pass',
 620: 'The Insider',
 621: 'The Finest Hours',
 622: 'Body of Lies',
 623: 'Dinner for Schmucks',
 624: 'Abraham Lincoln: Vampire Hunter',
 625: 'Entrapment',
 626: 'The X Files',
 627: 'The Last Legion',
 628: 'Saving Private Ryan',
 629: 'Need for Speed',
 630: 'What Women Want',
 631: 'Ice Age',
 632: 'Dreamcatcher',
 633: 'Lincoln',
 634: 'The Matrix',
 635: 'Apollo 13',
 636: 'The Santa Clause 2',
 637: 'Les Misérables',
 638: "You've Got Mail",
 639: 'Step Brothers',
 640: 'The Mask of Zorro',
 641: 'Due Date',
 642: 'Unbroken',
 643: 'Space Cowboys',
 644: 'Cliffhanger',
 645: 'Broken Arrow',
 646: 'The Kid',
 647: 'World Trade Center',
 648: 'Mona Lisa Smile',
 649: 'The Dictator',
 650: 'Eyes Wide Shut',
 651: 'Annie',
 652: 'Focus',
 653: 'This Means War',
 654: 'Blade: Trinity',
 655: 'Red Dawn',
 656: 'Primary Colors',
 657: 'Resident Evil: Retribution',
 658: 'Death Race',
 659: 'The Long Kiss Goodnight',
 660: 'Proof of Life',
 661: 'Zathura: A Space Adventure',
 662: 'Fight Club',
 663: 'We Are Marshall',
 664: 'Hudson Hawk',
 665: 'Lucky Numbers',
 666: 'I, Frankenstein',
 667: 'Oliver Twist',
 668: 'Elektra',
 669: 'Sin City: A Dame to Kill For',
 670: 'Random Hearts',
 671: 'Everest',
 672: 'Perfume: The Story of a Murderer',
 673: 'Austin Powers in Goldmember',
 674: 'Astro Boy',
 675: 'Jurassic Park',
 676: 'Wyatt Earp',
 677: 'Clear and Present Danger',
 678: 'Dragon Blade',
 679: 'Little Man',
 680: 'U-571',
 681: 'The American President',
 682: 'The Love Guru',
 683: '3000 Miles to Graceland',
 684: 'The Hateful Eight',
 685: 'Blades of Glory',
 686: 'Hop',
 687: '300',
 688: 'Meet the Fockers',
 689: 'Marley & Me',
 690: 'The Green Mile',
 691: 'Wild Hogs',
 692: 'Chicken Little',
 693: 'Gone Girl',
 694: 'The Bourne Identity',
 695: 'GoldenEye',
 696: "The General's Daughter",
 697: 'The Truman Show',
 698: 'The Prince of Egypt',
 699: 'Daddy Day Care',
 700: '2 Guns',
 701: 'Cats & Dogs',
 702: 'The Italian Job',
 703: 'Two Weeks Notice',
 704: 'Antz',
 705: 'Couples Retreat',
 706: 'Days of Thunder',
 707: 'Cheaper by the Dozen 2',
 708: 'Maze Runner: The Scorch Trials',
 709: 'Eat Pray Love',
 710: 'The Family Man',
 711: 'RED',
 712: 'Any Given Sunday',
 713: 'The Horse Whisperer',
 714: 'Collateral',
 715: 'The Scorpion King',
 716: 'Ladder 49',
 717: 'Jack Reacher',
 718: 'Deep Blue Sea',
 719: 'This Is It',
 720: 'Contagion',
 721: 'Kangaroo Jack',
 722: 'Coraline',
 723: 'The Happening',
 724: 'Man on Fire',
 725: 'The Shaggy Dog',
 726: 'Starsky & Hutch',
 727: 'Jingle All the Way',
 728: 'Hellboy',
 729: 'A Civil Action',
 730: 'ParaNorman',
 731: 'The Jackal',
 732: 'Paycheck',
 733: 'Up Close & Personal',
 734: 'The Tale of Despereaux',
 735: 'The Tuxedo',
 736: 'Under Siege 2: Dark Territory',
 737: 'Jack Ryan: Shadow Recruit',
 738: 'Joy',
 739: 'London Has Fallen',
 740: 'Alien: Resurrection',
 741: 'Shooter',
 742: 'The Boxtrolls',
 743: 'Practical Magic',
 744: 'The Lego Movie',
 745: 'Miss Congeniality 2: Armed and Fabulous',
 746: 'Reign of Fire',
 747: 'Gangster Squad',
 748: 'Year One',
 749: 'Invictus',
 750: 'State of Play',
 751: 'Duplicity',
 752: 'My Favorite Martian',
 753: 'The Sentinel',
 754: 'Planet 51',
 755: 'Star Trek: Nemesis',
 756: 'Intolerable Cruelty',
 757: 'Trouble with the Curve',
 758: 'Edge of Darkness',
 759: 'The Relic',
 760: 'Analyze That',
 761: 'Righteous Kill',
 762: 'Mercury Rising',
 763: 'The Soloist',
 764: 'The Legend of Bagger Vance',

In [ ]:
import pickle

In [ ]:
pickle.dump(new_df.to_dict(),open('movie_dict.pkl','wb'))

In [ ]:
pickle.dump(similarity,open('similarity.pkl','wb'))

In [ ]:
new_df.to_dict()